'use client'
import { useEffect, useState } from 'react'
import { useRouter } from 'next/navigation'
import { Heart, ArrowLeft, MessageCircle } from 'lucide-react'

export default function MatchesPage() {
  const router = useRouter(); const [matches, setMatches] = useState<{ id: string; userAId: string; userBId: string }[]>([]); const [error, setError] = useState('')
  useEffect(() => { fetch('/api/swipes').then(async (r) => { if (r.status === 401) return router.replace('/sign-in'); setMatches((await r.json()).matches || []) }).catch(() => setError('Không thể tải kết nối.')) }, [router])
  return <main className="min-h-screen bg-[#faf8f6] px-5 py-10 text-[#29231f]"><section className="mx-auto max-w-3xl"><button onClick={() => router.push('/')} className="mb-8 flex items-center gap-2 text-sm font-semibold text-[#9f1d35]"><ArrowLeft className="size-4" /> Khám phá</button><div className="flex items-end justify-between"><div><p className="text-sm font-semibold text-[#9f1d35]">Kết nối của bạn</p><h1 className="mt-2 font-serif text-4xl text-[#392b27]">Những người cùng nhịp</h1></div><Heart className="size-8 fill-[#f1c7c9] text-[#9f1d35]" /></div>{error && <p className="mt-8 text-sm text-red-700">{error}</p>}{!matches.length && !error && <div className="mt-10 rounded-3xl bg-white p-10 text-center shadow-sm ring-1 ring-[#eadfd8]"><Heart className="mx-auto size-10 text-[#cda8a0]" /><h2 className="mt-4 font-serif text-2xl">Chưa có match nào</h2><p className="mt-2 text-sm text-[#806e64]">Hãy tiếp tục khám phá để tìm người phù hợp.</p></div>}<div className="mt-8 grid gap-4 sm:grid-cols-2">{matches.map((match) => <article key={match.id} className="rounded-2xl bg-white p-5 shadow-sm ring-1 ring-[#eadfd8]"><div className="flex items-center gap-4"><div className="flex size-14 items-center justify-center rounded-full bg-[#f4e4dc] text-[#9f1d35]"><Heart className="size-6 fill-current" /></div><div><h2 className="font-semibold">Kết nối mới</h2><p className="text-sm text-[#806e64]">Hai bạn đã cùng quẹt phải</p></div></div><button onClick={() => router.push(`/chat?match=${match.id}`)} className="mt-5 flex w-full items-center justify-center gap-2 rounded-xl bg-[#9f1d35] px-4 py-3 text-sm font-semibold text-white"><MessageCircle className="size-4" /> Bắt đầu trò chuyện</button></article>)}</div></section></main>
}
